src/Entity/Orders.php
<?php

namespace App\Entity;

use App\Repository\OrdersRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: OrdersRepository::class)]
class Orders
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 8, scale: 2, nullable: true)]
    private ?string $total = null;

    #[ORM\ManyToOne(inversedBy: 'orders')]
    private ?Customers $customer = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $created_at = null;

    #[ORM\OneToMany(mappedBy: 'orders', targetEntity: OrderDetails::class)]
    private Collection $orderDetails;

    #[ORM\Column(length: 25)]
    private ?string $code_orders = null;

    public function __construct()
    {
        $this->orderDetails = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTotal(): ?string
    {
        return $this->total;
    }

    public function setTotal(?string $total): static
    {
        $this->total = $total;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(?\DateTimeInterface $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getCustomer(): ?Customers
    {
        return $this->customer;
    }

    public function setCustomer(?Customers $customer): static
    {
        $this->customer = $customer;

        return $this;
    }

    /**
     * @return Collection<int, OrderDetails>
     */
    public function getOrderDetails(): Collection
    {
        return $this->orderDetails;
    }

    public function addOrderDetail(OrderDetails $orderDetail): static
    {
        if (!$this->orderDetails->contains($orderDetail)) {
            $this->orderDetails->add($orderDetail);
            $orderDetail->setOrders($this);
        }

        return $this;
    }

    public function removeOrderDetail(OrderDetails $orderDetail): static
    {
        if ($this->orderDetails->removeElement($orderDetail)) {
            // set the owning side to null (unless already changed)
            if ($orderDetail->getOrders() === $this) {
                $orderDetail->setOrders(null);
            }
        }

        return $this;
    }

    public function getCodeOrders(): ?string
    {
        return $this->code_orders;
    }

    public function setCodeOrders(string $code_orders): static
    {
        $this->code_orders = $code_orders;

        return $this;
    }
}

src/Controller/OrdersController.php
<?php

namespace App\Controller;

use App\Entity\OrderDetails;
use App\Entity\Orders;
use App\Repository\CustomersRepository;
use App\Repository\OrderDetailsRepository;
use App\Repository\OrdersRepository;
use App\Repository\ProductsRepository;
use DateTime;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

use function PHPSTORM_META\map;

class OrdersController extends AbstractController
{
    #[Route('/orders', name: 'orders')]
    public function index(OrdersRepository $ordersRepository): Response
    {
        $orders = $ordersRepository->findall();

        return $this->render('orders/index.html.twig', [
            'orders' => $orders,
        ]);
    }

    public function show($id, OrdersRepository $ordersRepository):Response
    {
        $order = $ordersRepository->find($id);

        return $this->render('orders/detail.html.twig', [
            'order' => $order
        ]);
    }

    #[Route('/orders', name: 'orders_create')]
    public function create(
        CustomersRepository $customersRepository,
        ProductsRepository $productsRepository
    ):Response
    {
        $customers = $customersRepository->findall();
        $products = $productsRepository->findall();

        return $this->render('orders/create.html.twig', [
            'customers' => $customers,
            'products' => $products
        ]);
    }

    public function store(
        Request $request,
        OrdersRepository $ordersRepository,
        ProductsRepository $productsRepository,
        CustomersRepository $customersRepository,
        OrderDetailsRepository $orderDetailsRepository
    ): Response
    {
        $data_request = $request->request->all();
        $customers = $customersRepository->find($data_request['customer_id']);

        $order = new Orders();
        $order->setCreatedAt(new DateTime());
        $order->setCustomer($customers);
        $order->setTotal(0);
        $ordersRepository->save($order, true);

        $order_totals = 0;
        foreach($data_request['product_id'] as $key => $product) {
            $product = $productsRepository->find($product);
            $order_details = new OrderDetails();
            $order_details->setProduct($product);
            $order_details->setQuantity($data_request['quantity'][$key]);

            $total = $product->getPrice() * $order_details->getQuantity();

            $order_details->setTotal($total);
            $order_details->setOrders($order);
            $orderDetailsRepository->save($order_details, true);

            $order_totals += $total;
        }

        $order->setCodeOrders('KD-000'.$order->getId());
        $order->setTotal($order_totals);
        $ordersRepository->save($order, true);

        return $this->redirectToRoute('orders', [], 201);
    }

    public function edit(): Response
    {
        return $this->render('orders/edit.html.twig', [
            'order' => ''
        ]);
    }

    public function update(): Response
    {
        return $this->redirectToRoute('orders', [], 201);
    }

    public function delete(
        $id, 
        OrdersRepository $ordersRepository
    ): Response
    {
        $order = $ordersRepository->find($id);

        if(!$order) {
            return $this->redirectToRoute('orders', [], 301);
        }

        $ordersRepository->remove($order, true);

        return $this->redirectToRoute('orders', [], 301);
    }
}

templates/orders/create.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="w-full mx-auto px-5">
        <h1 class="text-3xl font-bold underline my-8">Order Pages</h1>

        <div class="flex justify-between items-center my-8">
            <h3 class="text-2xl font-bold">Create Orders</h3>
        </div>
        <div class="w-1/4">
            <form action="/orders/store" method="POST">
                <div class="flex flex-col gap-3 mb-5">
                    <label
                        for="name"
                        class="text-lg"
                        >Customers
                    </label>
                    <select name="customer_id" class="border rounded p-3">
                        <option>Please Choose Option</option>
                        {% for customer in customers %}
                            <option value="{{ customer.id }}">{{ customer.name }}</option>
                        {% endfor %}
                    </select>
                </div>

                <button type="button" class="px-2 bg-blue-500 py-2 rounded text-white mb-5" id="add-data">Add Data</button>
                <div class="mx-auto">
                    <table id="tableOrders" class="table table-auto border-collapse border border-slate-500 w-full">
                        <thead>
                            <tr>
                                <th class="border border-slate-600">Products</th>
                                <th class="border border-slate-600">Quantity</th>
                                <th class="border border-slate-600">Opsi</th>
                            </tr>
                        </thead>
                        <tbody>  
                            <tr>
                                <td class="border border-slate-600 p-5">
                                    <select name="product_id[]" id="product_id" class="border rounded p-3">
                                        <option>Please Choose Option</option>
                                        {% for product in products %}
                                            <option value="{{ product.id }}">{{ product.name }} - {{ product.price }}</option>
                                        {% endfor %}
                                    </select>
                                </td>
                                <td class="border border-slate-600 p-5">
                                    <input
                                        type="number"
                                        class="p-3 border rounded"
                                        id="quantity"
                                        name="quantity[]"
                                        min="0" 
                                    />
                                </td>
                                <td class="border border-slate-600 p-5">
                                    <div class="flex gap-3">
                                        <button type="button" class="px-2 bg-red-500 py-2 rounded text-white" onclick="remove_data_order(this)">Remove</button>
                                    </div>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <div class="mt-2">
                    <button class="px-2 bg-green-500 py-2 rounded text-white">Save</button>
                    <a href="/orders" class="px-2 bg-red-500 py-2 rounded text-white">Cancel</a>
                </div>
            </form>
        </div>
    </div>

    <script>
        document.addEventListener("DOMContentLoaded", () => {
            document.getElementById('add-data').addEventListener('click', function() {
                create_data_order()
            })
        });

        function create_data_order() {
            let tbody = document.getElementById('tableOrders').getElementsByTagName('tbody');
            let tr = document.createElement('tr')
            let data = `
                <td class="border border-slate-600 p-5">
                    <select name="product_id[]" id="product_id" class="border rounded p-3">
                        <option>Please Choose Option</option>
                        {% for product in products %}
                            <option value="{{ product.id }}">{{ product.name }} - {{ product.price }}</option>
                        {% endfor %}
                    </select>
                </td>
                <td class="border border-slate-600 p-5">
                    <input
                        type="number"
                        class="p-3 border rounded"
                        id="quantity"
                        name="quantity[]"
                        min="0" 
                    />
                </td>
                <td class="border border-slate-600 p-5">
                    <div class="flex gap-3">
                        <button type="button" class="px-2 bg-red-500 py-2 rounded text-white" onclick="remove_data_order(this)">Remove</button>
                    </div>
                </td>
            `

            tr.innerHTML = data

            let newRow = tbody[0].appendChild(tr);
        }

        function remove_data_order(e) {
            e.parentNode.parentNode.parentNode.remove()
        }
    </script>
{% endblock %}

templates/orders/detail.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello Orders!{% endblock %}

{% block body %}
<div class="w-full mx-auto px-5">
        <h1 class="text-3xl font-bold underline my-8">Orders Pages</h1>

        <div class="flex flex-col my-8">
            <p class="text-2xl font-bold">Order Code : {{ order.codeOrders }}</p>
            <p class="text-2xl font-bold">Nama : {{ order.customer.name }}</p>
            <p class="text-2xl font-bold">total : {{ order.total|number_format('0', ',', '.') }}</p>
        </div>

        <div class="flex justify-between items-center my-8">
            <h3 class="text-2xl font-bold">List Orders</h3>
        </div>
        <div class="mx-auto">
            <table class="table table-auto border-collapse border border-slate-500 w-full">
                <thead>
                    <tr>
                        <th class="border border-slate-600">Product</th>
                        <th class="border border-slate-600">Quantity</th>
                        <th class="border border-slate-600">Total</th>
                    </tr>
                </thead>
                <tbody>
                    {% for data in order.orderDetails %}    
                        <tr>
                            <td class="border border-slate-600 p-5">{{ data.product.name }}</td>
                            <td class="border border-slate-600 p-5">{{ data.quantity }}</td>
                            <td class="border border-slate-600 p-5">Rp. {{ data.total|number_format('0', ',', '.') }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

templates/orders/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello Orders!{% endblock %}

{% block body %}
<div class="w-full mx-auto px-5">
        <h1 class="text-3xl font-bold underline my-8">Orders Pages</h1>

        <div class="flex justify-between items-center my-8">
            <h3 class="text-2xl font-bold">List Orders</h3>
            <a href="/orders/create" class="px-2 bg-blue-500 py-2 rounded text-white">Create Data</a>
        </div>
        <div class="mx-auto">
            <table class="table table-auto border-collapse border border-slate-500 w-full">
                <thead>
                    <tr>
                        <th class="border border-slate-600">Code Order</th>
                        <th class="border border-slate-600">Total</th>
                        <th class="border border-slate-600">Customers</th>
                        <th class="border border-slate-600">Opsi</th>
                    </tr>
                </thead>
                <tbody>
                    {% for data in orders %}    
                        <tr>
                            <td class="border border-slate-600 p-5">{{ data.codeOrders }}</td>
                            <td class="border border-slate-600 p-5">Rp. {{ data.total|number_format('0', ',', '.') }}</td>
                            <td class="border border-slate-600 p-5">{{ data.customer.name}}</td>
                            <td class="border border-slate-600 p-5">
                                <div class="flex gap-3">
                                    <a href="/orders/{{ data.id }}/detail" class="px-2 bg-gray-500 py-2 rounded text-white">Detail</a>
                                    {# <a href="/products/{{ data.id }}/edit" class="px-2 bg-green-500 py-2 rounded text-white">Edit</a> #}
                                    {# <a href="/orders/{{ data.id }}/delete" class="px-2 bg-red-500 py-2 rounded text-white">Delete</a> #}
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}